---
- name: Stop a specific Hyper-V VM
  hosts: hyperv_hosts
  gather_facts: false

  vars_prompt:
      - name: vm_name
        prompt: "Enter the name of the VM to stop"
        private: no

  tasks:
      - name: Stop the VM
        win_shell: |
            Stop-VM -Name "{{ vm_name }}" -Force
        register: stop_result
        ignore_errors: yes

      - name: Show stop VM result
        debug:
            var: stop_result.stdout
