# Fedora base image
FROM fedora:latest

# Install ansible-core + virt-v2v
RUN dnf -y install ansible-core virt-v2v && \
    dnf clean all

# Copy your playbook into the image
COPY convert.yaml /opt/convert.yaml

# Default entrypoint runs the playbook
ENTRYPOINT ["ansible-playbook", "/opt/convert.yaml"]
