---
- name: V2V Migration Playbook
  hosts: localhost
  gather_facts: no

  vars:
    in_dir: "{{ lookup('env', 'IN') | default('/input', true) }}"
    out_dir: "{{ lookup('env', 'OUT') | default('/output', true) }}"
    input_ext: "{{ lookup('env', 'INPUT_EXT') | default('vhd', true) }}"

  tasks:
    - name: Find input files
      ansible.builtin.find:
         paths: "{{ in_dir }}"
         patterns: "{{ '*.' + input_ext }}"
         recurse: true
      register: found_files


    - name: Show found files
      debug:
        var: found_files.files | map(attribute='path') | list

    - name: Convert each disk with virt-v2v
      ansible.builtin.command:
        argv:
          - virt-v2v
          - -i
          - disk
          - -o
          - local
          - -os
          - "{{ out_dir }}/{{ item.path | regex_replace('^' + in_dir + '/', '') | dirname }}"
          - "{{ item.path }}"
      loop: "{{ found_files.files }}"


      
